<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-23 at 12:45:21.
 */
class PdoGsbTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PdoGsb
     */
    protected $monPdoTest;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
         require_once("../include/class.pdogsb.inc.php") ;
         
         
        
        $this->monPdoTest = PdoGsb::getPdoGsb();
        
        PdoGsb::getPdo()->exec("SET AUTOCOMMIT OFF;");
        
        PdoGsb::getPdo()->beginTransaction();
    
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
        PdoGsb::getPdo()->rollBack();
        PdoGsb::getPdo()->exec("SET AUTOCOMMIT ON;");
        
    }

    /**
     * @covers PdoGsb::_destruct
     * @todo   Implement test_destruct().
     */
    /*public function test_destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }*/
    /**
     * @covers PdoGsb::getPdoGsb
     * @todo   Implement testGetPdoGsb().
     */
    
    public function testGetPdoGsb() {
        // Remove the following lines when you implement this test.
       $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getInfosVisiteur
     * @todo   Implement testGetInfosVisiteur().
     */
    public function testGetInfosVisiteur() {
        // Remove the following lines when you implement this test.
        $visiteur = array (
           'id' =>'a131',
            'nom' => "Villechalane" ,
            'prenom' => "Louis"
            
        ); 

       $return = $this->monPdoTest->getInfosVisiteur('lvillachane', md5('jux7g')) ;
        
       $this->assertSame($visiteur,$return);
        
    }

    /**
     * @covers PdoGsb::getInfosComptable
     * @todo   Implement testGetInfosComptable().
     */
    public function testGetInfosComptable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesFraisHorsForfait
     * @todo   Implement testGetLesFraisHorsForfait().
     */
    public function testGetLesFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getNbjustificatifs
     * @todo   Implement testGetNbjustificatifs().
     */
    public function testGetNbjustificatifs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesFraisForfait
     * @todo   Implement testGetLesFraisForfait().
     */
    public function testGetLesFraisForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesIdFrais
     * @todo   Implement testGetLesIdFrais().
     */
    public function testGetLesIdFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majFraisForfait
     * @todo   Implement testMajFraisForfait().
     */
    public function testMajFraisForfait() {
        // Remove the following lines when you implement this test.
         $fiche = array (
            'ETP' => '2',
            );
        $this->monPdoTest->majFraisForfait("a131", "201002", $fiche);
        
        $req = "SELECT lignefraisforfait.quantite
                FROM lignefraisforfait
                WHERE lignefraisforfait.idvisiteur = 'a131'
                AND lignefraisforfait.mois = '201002'
                AND lignefraisforfait.idfraisforfait = 'ETP'";
        $res = PdoGsb::getPdo()->query($req);
        $etat = $res->fetch(PDO::FETCH_ASSOC);

        $qte = array (
            'quantite' => '2');
        
        $this->assertEquals($qte, $etat);       
    }

    /**
     * @covers PdoGsb::majNbJustificatifs
     * @todo   Implement testMajNbJustificatifs().
     */
    public function testMajNbJustificatifs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::estPremierFraisMois
     * @todo   Implement testEstPremierFraisMois().
     */
    public function testEstPremierFraisMois() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::dernierMoisSaisi
     * @todo   Implement testDernierMoisSaisi().
     */
    public function testDernierMoisSaisi() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::creeNouvellesLignesFrais
     * @todo   Implement testCreeNouvellesLignesFrais().
     */
    public function testCreeNouvellesLignesFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::creeNouveauFraisHorsForfait
     * @todo   Implement testCreeNouveauFraisHorsForfait().
     */
    public function testCreeNouveauFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::supprimerFraisHorsForfait
     * @todo   Implement testSupprimerFraisHorsForfait().
     */
    public function testSupprimerFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesMoisDisponibles
     * @todo   Implement testGetLesMoisDisponibles().
     */
    public function testGetLesMoisDisponibles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesMoisEnAttente
     * @todo   Implement testGetLesMoisEnAttente().
     */
    public function testGetLesMoisEnAttente() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesVisiteurs
     * @todo   Implement testGetLesVisiteurs().
     */
    public function testGetLesVisiteurs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesInfosFicheFrais
     * @todo   Implement testGetLesInfosFicheFrais().
     */
    public function testGetLesInfosFicheFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getLesFichesFrais
     * @todo   Implement testGetLesFichesFrais().
     */
    public function testGetLesFichesFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majEtatFicheFrais
     * @todo   Implement testMajEtatFicheFrais().
     */
    public function testMajEtatFicheFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::majEtatFicheFraisSuivi
     * @todo   Implement testMajEtatFicheFraisSuivi().
     */
    public function testMajEtatFicheFraisSuivi() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::reportDFraisHorsForfait
     * @todo   Implement testReportDFraisHorsForfait().
     */
    public function testReportDFraisHorsForfait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PdoGsb::getNomPrenomVisiteur
     * @todo   Implement testGetNomPrenomVisiteur().
     */
    public function testGetNomPrenomVisiteur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
